description: "Astro components desigend for static sites using modern styles, css variables, minimal html, accessibility."
keywords: "Astro, components, static site generator, ssg, accessibility, semantic html"
title: "Astro Components"

social:
  facebook:
    handle: "oeu"
  instagram:
    handle: "oeu"

theme:
  palette: 
    base:     "#0f1117"
    surface:  "#161a23"
    accent-1: "#4f46e5"
    accent-2: "#22d3ee"
    accent-3: "#e5e7eb"
  palette-purple:
    base: "#ececec"
    surface: "#abaab8"
    accent-1: "#474787"
    accent-2: "#2d2c54"
  palette-matcha:
    base: "fcfcfc"
    surface: "#f1ebe1"
    accent-1: "#c0cfb2"
    accent-2: "#44624a"
    accent-3: "#8ba888"
  font:
    heading:
      family: "Inter"
    body:
      family: 'ClassicalHumanist'
  typography:
    line-height: '1.5rem'
