title: "Website Serialization Schema Validation"
type: object
additionalProperties: false
required: ["meta","pages","globals"]

properties:
  meta:
    $ref: './meta.yaml'

  pages:
    type: object
    additionalProperties: false
    description: A set of pages for the website. The property name is the path. Each one needs a title, an array of blocks, and optionally metadata.
    minProperties: 1
    examples:
      - { "/": {title: "home", blocks: []}, "/about": {title: "about", blocks: []}, "/blog": {title: "blog", blocks: []}, "/contact": {title: "contact", blocks: []}}
      - { "/": {title: "home", blocks: []}, "/about": {title: "about", blocks: []}, "/services": {title: "services", blocks: []}, "/contact": {title: "contact", blocks: []}, "/products": {title: "products", blocks: []}}
    patternProperties:
      "^/(?:[a-z0-9\\-_.~]+(?:/[a-z0-9\\-_.~]+)*)?$":
        type: object
        required: ["title","blocks"]
        additionalProperties: true
        properties:
          globals:
            type: array
            description: An array specifying which globals to include.
            default: ["Navbar","Footer"]
          title:
            type: string
          blocks:
            type: array
            items:
              type: object

  global:
    type: array
    description: A List of Global Components
    default: [{title: Navbar},{title: Footer}]
