title: "Webpage Serialization Schema Validation"
type: object
additionalProperties: false
required: ["meta","pages","globals"]

properties:
  meta:
    $ref: './meta.yaml'

  blocks:
    type: array
    items:

  global:
    type: array
    description: A List of Global Components
    default: [{title: Navbar},{title: Footer}]
