meta:
  title: The Local Restaurant
  author: John Doe
  description: A delicious local restaurant serving up fresh and tasty food.
  image: https://example.com/local_restaurant.jpg
  iso_country: US
  iso_language: en
  keywords: local, restaurant, food, delicious
  card: summary_large_image
  url: https://example.com/local-restaurant
  type: website
  robots: index, follow
  fbAppId: null
  latitude: 37.421955
  longitude: -122.084058
  revenge: false
  theme:
    palette:
      id: local-restaurant
      title: Local Restaurant
      author: John Doe
      colors:
        base: '#000000'
        surface: '#ffffff'
        brand: '#f28b31'
        accent: '#95c4ce'
        support: '#6d756e'
    fonts:
      heading: Roboto
      body: Open Sans
  icon:
    main: /favicon.svg
    legacy: /favicon.ico
    small: /favicon.svg
    large: /favicon.svg
  social:
    twitter: null
    facebook: null
    telegram: null
    mastodon: null
    bluesky: null
pages:
  "/":
    title: "home"
    blocks:
    - component: Hero
      headline: Our Restaurant
      subheadline: Delicious Food for All Seasons
      ctaPrimaryText: Order Now
      ctaPrimaryAction: tel:1234567890
      ctaSecondaryText: Get Reviews
      ctaSecondaryAction: '#reviews'
      googleReviewLink: ''
      imgSrc: https://example.com/images/restaurant-food.jpg
      imgAlt: Restaurant Food
      icon: fas fa-utensils
      style: 'background-color: #FFC800; color: #222222; font-size: 36px;'
      imgOpacity: '.4'
      backgroundColor: '#FFFFFF'
      height: 100vh
