meta:
  font-heading: "Playfair Display"
  font-body: "Lato"
  color-base: "whitesmoke"
  color-surface: "gray"
  color-brand: ""
  color-accent: ""
  color-support: ""
pages: 
  "/": "./home.yaml"
  "about": "./about.yaml"
  "professionals": "./professionals.yaml"
  "contact": "./contact.yaml"
