title: "Website Serialization Schema Validation"
type: object
additionalProperties: false
required: ["meta","pages","globals"]

properties:
  meta:
    $ref: './meta.yaml'

  pages:
    type: object
    additionalProperties: false
    examples:
      - { "/": {title: "home", blocks: []}, "/about": {title: "about", blocks: []}, "/services": {title: "services", blocks: []}, "/contact": {title: "contact", blocks: []}}
    patternProperties:
      "^/(?:[a-z0-9\\-_.~]+(?:/[a-z0-9\\-_.~]+)*)?$":
        type: object
        required: ["title","blocks"]
        additionalProperties: true
        properties:
          title:
            type: string
          blocks:
            type: array
            items:
              type: object

  global:
    type: array
    description: A List of Global Components
    default: [{title: NavBar},{title: Footer}]
