#$schema: "https://json-schema.org/draft/2020-12/schema"
title: "Website Serialization Schema Validation"
type: object
additionalProperties: false

properties:
  meta:
    type: object
    required:
      - title
      - description
      - image
      - keywords
      - card
      - url
      - type
      - robots
      - revenge
      - color
      - icon
    properties:
      title:
        type: string
      author:
        type: string
      description:
        type: string
      image:
        type: string
        format: uri
      iso_country:
        type: string
      iso_language:
        type: string
      keywords:
        type: string
      card:
        type: string
      url:
        type: string
        format: uri
      type:
        type: string
      robots:
        type: string
      fbAppId:
        type: string
      latitude:
        type: string
      longitude:
        type: string
      revenge:
        type: boolean
      fonts:
        type: object
        required: [heading, body]
        properties:
          heading: { type: string }
          body: { type: string }
      color:
        type: object
        properties:
          base: { type: string }
          surface: { type: string }
          brand: { type: string }
          accent: { type: string }
          support: { type: string }
          theme: { type: string }
          themeLight: { type: string }
          themeDark: { type: string }
      icon:
        type: object
        properties:
          main: { type: string }
          legacy: { type: string }
          small: { type: string }
          large: { type: string }
      social:
        type: object
        properties:
          twitter: { type: string }

  pages:
    type: object

  global:
    type: array
    description: A List of Global Components
